### ISSUE TITLE
All image link no longer exist

### ISSUE THREAD

**Issue by ROMVoid95** [r00t-3xp10it/hacking-material-books#2]
Taking a shot in the dark with this one, but any chance the images referenced in the repo still exist? the tinypic urls no longer exists. Thanks! and great writting!

**Comment by r00t-3xp10it** [comment]
well ... i need to take new screenshots ... but iam lazy to do what i have done before ..

**Comment by ROMVoid95** [comment]
Hey there, thanks for actually replying to this, It's not a problem. It was, as stated, a shot in the dark :) I appreciate the reply and work done in the repo!
